### ISSUE TITLE
How to show popup, screen if deltaTime = 0

### ISSUE THREAD

**Issue by takaaptech** [Xerios/ScreenManager#7]
Hi,
When I pause the game using deltaTime = 0f, OpenScreen or Popup does not work (Maybe because of using couroutine ). How can we pass this?
Thank so much!

**Comment by Xerios** [comment]
Use unscaledDeltaTime, that should make the animation play independently from timeScale changes

**Comment by takaaptech** [comment]
No, When I use Time.deltaTime = 0 for pause the game. Then when I want to show pause popup from screen manager, the framework does not show the screen.

**Comment by Xerios** [comment]
That's because the screen class which handles the animation uses unscaledDeltaTime by default. 
If you change `Time.timeScale` ( because I'm pretty sure that `Time.deltaTime` is readonly ), you affect everything that uses deltaTime, therefore you pause the animations as well.

The trick is, depending on what animation class you're using and how you're animating your screens, is to use https://docs.unity3d.com/ScriptReference/Time-unscaledDeltaTime.html. LeanTween has this option somewhere, animator does as well.

**Comment by takaaptech** [comment]
Ah, Thank you, i see your point.
But when I write simple Screen extend BaseScreen, In OnAnimationIn and OnAnimationOut I do nothing just call immediately  OnAnimationInEnd, OnAnimationOutEnd, The screen still do not show. (Or I just add BaseScreen as component, it is the same)
I think my problem was the function CoroutineUpdate in ScreenManager using WaitForSeconds inside the loop.
Can you have a deep look into that?
Thank so much!

**Comment by Xerios** [comment]
You could be right. Try replacing `WaitForSeconds` by http://answers.unity3d.com/questions/301868/yield-waitforseconds-outside-of-timescale.html

I'm really busy lately so I won't be able to help you anytime soon, although if you fix this, a pull request would be much appreciated :)

**Comment by takaaptech** [comment]
Ok I just test and create pull request here:
https://github.com/Xerios/ScreenManager/pull/8
Thank you so much!
